import { Channel, User } from '@prisma/client'
import type { GetStaticPathsResult, GetStaticProps, GetStaticPropsContext, GetStaticPropsResult, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { db } from '../util/db'

type Props = {
  channels: (Channel & {
    users: User[];
  })[]
}
const Home: NextPage<Props> = (props) => {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Yondr Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center h-1/2">
        {props.channels.map((channel, index) => (
          <div>
            <h1>
              {channel.name}
            </h1>
            <div>
              {/* Users in the channel */}
            </div>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export const getStaticProps = async (ctx: GetStaticPropsContext): Promise<GetStaticPropsResult<Props>> => {
  const channels = await db.channel.findMany({
    include: {
      users: true
    }
  })
  return {
    props: {
      channels
    }
  }
}
export default Home
